### ISSUE TITLE
org-linker-edna-schedule: add quotes

### ISSUE THREAD

**Issue by novoid** [toshism/org-linker-edna#1]
org-edna interprets `scheduled!(".")` as "today". If user is entering only the dot, `org-linker-edna-schedule` should add the necessary quotes for convenience purpose.

Update 2020-09-25: Actually, according to [the manual](https://www.nongnu.org/org-edna-el/) _all_ entries for "scheduled!()" require the quotes.

**Comment by toshism** [comment]
I _think_ this should be fixed now. I just pushed a batch of changes. It changes the interface quite a bit as well. I'll leave this open until you validate it's actually working though.

**Comment by novoid** [comment]
OMG, while reviewing the changes, I noticed that I forgot to replace occurrences of `org-super-links` in the README. Embarrassing.

**Comment by toshism** [comment]
haha, no worries. 

I'll also mention in the helm menu where you select the trigger actions you can select multiple with `C-Space` to set multiple actions at once.

**Comment by novoid** [comment]
Works:

```
*** fix678
:PROPERTIES:
:CREATED:  [2020-10-03 Sat 11:17]
:ID:       2020-10-03-fix678
:TRIGGER:  ids(2020-10-03-fix987) todo!(NEXT) scheduled!(".")
:END:

*** fix987
:PROPERTIES:
:CREATED:  [2020-10-03 Sat 11:17]
:ID:       2020-10-03-fix987
:BLOCKER:  ids(2020-10-03-fix678)
:END:
```

`C-SPC` is awesome. However, if there is any chance that you might add it as some context help in the helm dialog, this would be perfect. At least to me, this binding within the helm dialog was new.

However, #4 is still an open bug.
