### ISSUE TITLE
Please, remove the dependency on the helm completion package.

### ISSUE THREAD

**Issue by MorphicResonance** [toshism/org-linker-edna#15]
It can be seen that by installing the package, you cannot do without installation of an additional package from a third party by default. 
![Screenshot_20221109_013646](https://github.com/toshism/org-linker-edna/assets/55984436/90994803-7aaf-4bea-9bec-2e52467bf58c)

 With the need to install a package like helm, we end up in dependencies hell. Helm dependency was removed for org-super-links which is good.

It's just amazing why developers release packages that don't
working by default with built-in and fully working parts of
emacs, but those that requiring the connection of something else.

**Comment by toshism** [comment]
amazing eh? :D but yeah, helm is a dependency. I should update the readme to mention it, but I probably won't be removing it anytime soon. I'm not positive what this would look like without helm really. That being said if you want to take a shot at removing it I'd be happy to advise where necessary.
