### ISSUE TITLE
Provide README.org file

### ISSUE THREAD

**Issue by novoid** [toshism/org-linker-edna#2]
This looks great from first try!

You should definitely add a README file so that others might understand, what diamond they have found.

I can support you here, if you wan. My READMEs look different but I'm happy to adapt https://github.com/toshism/org-super-links/blob/develop/README.org for this repository and send it as a pull request so that you can fix my errors.

**Comment by toshism** [comment]
awesome, thanks for all the feedback. it just may motivate me to put some more work in on this :D 

It would be awesome if you want to contribute a readme. I'm actually not super particular about the style, so if you would like, that would be great!

**Comment by novoid** [comment]
It's a rainy Saturday tomorrow. Let's see what it might bring us ;-)

**Comment by novoid** [comment]
Perfect timing - yesterday, I published https://karl-voit.at/2020/10/01/org-depend-to-edna/ and did some advertising for org-linker-edna.

**Comment by toshism** [comment]
ha perfect! and thanks!
