### ISSUE TITLE
org-linker-edna-get-or-create-id-for-marker should respect sl-pre-link-hook (org-super-links)

### ISSUE THREAD

**Issue by novoid** [toshism/org-linker-edna#3]
Hi,

With `sl-pre-link-hook` and `sl-pre-backlink-hook` you've got a wonderful method to customize the generation of IDs.

I'd love to have the very same mechanism here, since I don't like UUIDs and prefer human-readable IDs for which I do have my own function. This would be great to have with `org-linker-edna` as well.

**Comment by toshism** [comment]
@novoid try setting `link-id-function` to your custom id function and let me know if that works for you. 

default is here https://github.com/toshism/org-linker-edna/blob/master/org-linker-edna.el#L35

**Comment by novoid** [comment]
Awesome!

```
(setq link-id-function 'my-id-get-or-generate)
```
... works as expected. Thanks for the tip!
