### ISSUE TITLE
Prepend IDs with "id:" to make them navigable

### ISSUE THREAD

**Issue by novoid** [toshism/org-linker-edna#5]
Starting with `org-edna` version 1.1.2, this is a valid syntax:
```
** Test heading
:PROPERTIES:
:TRIGGER: ids("id:foo" "id:bar") todo!(NEXT)
:END:

** Foo heading
:PROPERTIES:
:ID: foo
:END:
** Bar heading
:PROPERTIES:
:ID: bar
:END:

```

This has the advantage, that the IDs within the `ids()` property are clickable links to their destination headings.
I'd love to see those `id:` prefixes added by `org-linker-edna` so that dependencies are also navigable links.

**Comment by toshism** [comment]
So, I'm not actually totally clear exactly how triggers with multiple ids should really be formatted. If you want to try out the change I just pushed let me know if it's correct.

**Comment by novoid** [comment]
I'm sorry that I was using an example with multiple targets, which is _not_ the main purpose of this ticket.
The main goal is to use `ids(id:foo)` instead of `ids(foo)` or - for non-UUID items as outlined in #4 `ids("id:foo")` instead of `ids("foo")`.

Both are not present in the latest changes.

**Comment by novoid** [comment]
Just a remark: the `id:` prefix also works for UUIDs. So if you're using UUIDs, you probably also want to have those prefixes there.
I don't so it's not relevant to me personally.
