### ISSUE TITLE
Divergent format when assigning a second dependency

### ISSUE THREAD

**Issue by novoid** [toshism/org-linker-edna#8]
Here is the result after assigning two dependencies to the "foo89" heading:

```
****** foo89
:PROPERTIES:
:CREATED:  [2020-11-26 Thu 10:09]
:ID:       2020-11-26-foo89
:TRIGGER:  ids("id:2020-11-26-bar89") scheduled!(".") ids(2020-11-26-baz89) todo!(NEXT) scheduled!(".")
:END:

****** bar89
:PROPERTIES:
:CREATED:  [2020-11-26 Thu 10:09]
:ID:       2020-11-26-bar89
:BLOCKER:  ids("id:2020-11-26-foo89")
:END:

****** baz89
:PROPERTIES:
:CREATED:  [2020-11-26 Thu 10:09]
:ID:       2020-11-26-baz89
:BLOCKER:  ids("id:2020-11-26-foo89")
:END:
```

As you can see, the second one is `ids(2020-11-26-baz89)` while I would assume `ids("id:2020-11-26-baz89")` just like the first one.

**Comment by toshism** [comment]
Hey, thanks @novoid . This is from a failed attempt at some duplication checking. For now I'll just remove it. This means that adding a trigger twice to the same target will result in duplication though.

I'll have to work on a better dupe check at some point.
